/**
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.air;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.airlineregistration.air.AirPackage
 * @generated
 */
public interface AirFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AirFactory eINSTANCE = org.xtext.airlineregistration.air.impl.AirFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity</em>'.
   * @generated
   */
  Entity createEntity();

  /**
   * Returns a new object of class '<em>Airport</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Airport</em>'.
   * @generated
   */
  Airport createAirport();

  /**
   * Returns a new object of class '<em>Airline</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Airline</em>'.
   * @generated
   */
  Airline createAirline();

  /**
   * Returns a new object of class '<em>Airplane</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Airplane</em>'.
   * @generated
   */
  Airplane createAirplane();

  /**
   * Returns a new object of class '<em>Scheduled Flight</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scheduled Flight</em>'.
   * @generated
   */
  ScheduledFlight createScheduledFlight();

  /**
   * Returns a new object of class '<em>Specific Flight</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Specific Flight</em>'.
   * @generated
   */
  SpecificFlight createSpecificFlight();

  /**
   * Returns a new object of class '<em>Schedule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Schedule</em>'.
   * @generated
   */
  Schedule createSchedule();

  /**
   * Returns a new object of class '<em>Employee</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Employee</em>'.
   * @generated
   */
  Employee createEmployee();

  /**
   * Returns a new object of class '<em>Pilot</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pilot</em>'.
   * @generated
   */
  Pilot createPilot();

  /**
   * Returns a new object of class '<em>Flight Attendant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Flight Attendant</em>'.
   * @generated
   */
  FlightAttendant createFlightAttendant();

  /**
   * Returns a new object of class '<em>Bag Handler</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bag Handler</em>'.
   * @generated
   */
  BagHandler createBagHandler();

  /**
   * Returns a new object of class '<em>Gate Personnel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Gate Personnel</em>'.
   * @generated
   */
  GatePersonnel createGatePersonnel();

  /**
   * Returns a new object of class '<em>Passenger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Passenger</em>'.
   * @generated
   */
  Passenger createPassenger();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AirPackage getAirPackage();

} //AirFactory
