/**
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.air;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.airlineregistration.air.AirFactory
 * @model kind="package"
 * @generated
 */
public interface AirPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "air";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/airlineregistration/Air";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "air";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AirPackage eINSTANCE = org.xtext.airlineregistration.air.impl.AirPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.ModelImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ENTITIES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.EntityImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = 0;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.AirportImpl <em>Airport</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.AirportImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getAirport()
   * @generated
   */
  int AIRPORT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT__NAME = ENTITY__NAME;

  /**
   * The feature id for the '<em><b>Aname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT__ANAME = ENTITY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT__LOCATION = ENTITY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Airport</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.AirlineImpl <em>Airline</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.AirlineImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getAirline()
   * @generated
   */
  int AIRLINE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRLINE__NAME = ENTITY__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRLINE__DESCRIPTION = ENTITY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Airline</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRLINE_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.AirplaneImpl <em>Airplane</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.AirplaneImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getAirplane()
   * @generated
   */
  int AIRPLANE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPLANE__NAME = ENTITY__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPLANE__TYPE = ENTITY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Seats</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPLANE__SEATS = ENTITY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Airplane</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPLANE_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.ScheduledFlightImpl <em>Scheduled Flight</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.ScheduledFlightImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getScheduledFlight()
   * @generated
   */
  int SCHEDULED_FLIGHT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULED_FLIGHT__NAME = ENTITY__NAME;

  /**
   * The feature id for the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULED_FLIGHT__FROM = ENTITY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULED_FLIGHT__TO = ENTITY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Airline</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULED_FLIGHT__AIRLINE = ENTITY_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULED_FLIGHT__TIME = ENTITY_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Scheduled Flight</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULED_FLIGHT_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.SpecificFlightImpl <em>Specific Flight</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.SpecificFlightImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getSpecificFlight()
   * @generated
   */
  int SPECIFIC_FLIGHT = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFIC_FLIGHT__NAME = ENTITY__NAME;

  /**
   * The feature id for the '<em><b>Fname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFIC_FLIGHT__FNAME = ENTITY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Scheduled Flight</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFIC_FLIGHT__SCHEDULED_FLIGHT = ENTITY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFIC_FLIGHT__DATE = ENTITY_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Pilot</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFIC_FLIGHT__PILOT = ENTITY_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Plane</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFIC_FLIGHT__PLANE = ENTITY_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Staff</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFIC_FLIGHT__STAFF = ENTITY_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Specific Flight</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFIC_FLIGHT_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.ScheduleImpl <em>Schedule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.ScheduleImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getSchedule()
   * @generated
   */
  int SCHEDULE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULE__NAME = ENTITY__NAME;

  /**
   * The feature id for the '<em><b>Specific Flights</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULE__SPECIFIC_FLIGHTS = ENTITY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Schedule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULE_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.EmployeeImpl <em>Employee</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.EmployeeImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getEmployee()
   * @generated
   */
  int EMPLOYEE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE__NAME = ENTITY__NAME;

  /**
   * The number of structural features of the '<em>Employee</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.PilotImpl <em>Pilot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.PilotImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getPilot()
   * @generated
   */
  int PILOT = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PILOT__NAME = EMPLOYEE__NAME;

  /**
   * The feature id for the '<em><b>Piname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PILOT__PINAME = EMPLOYEE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Airline</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PILOT__AIRLINE = EMPLOYEE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Pilot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PILOT_FEATURE_COUNT = EMPLOYEE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.FlightAttendantImpl <em>Flight Attendant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.FlightAttendantImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getFlightAttendant()
   * @generated
   */
  int FLIGHT_ATTENDANT = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT_ATTENDANT__NAME = EMPLOYEE__NAME;

  /**
   * The feature id for the '<em><b>Faname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT_ATTENDANT__FANAME = EMPLOYEE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Airline</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT_ATTENDANT__AIRLINE = EMPLOYEE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Flight Attendant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT_ATTENDANT_FEATURE_COUNT = EMPLOYEE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.BagHandlerImpl <em>Bag Handler</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.BagHandlerImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getBagHandler()
   * @generated
   */
  int BAG_HANDLER = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BAG_HANDLER__NAME = EMPLOYEE__NAME;

  /**
   * The feature id for the '<em><b>Bhname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BAG_HANDLER__BHNAME = EMPLOYEE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Airport</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BAG_HANDLER__AIRPORT = EMPLOYEE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Bag Handler</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BAG_HANDLER_FEATURE_COUNT = EMPLOYEE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.GatePersonnelImpl <em>Gate Personnel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.GatePersonnelImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getGatePersonnel()
   * @generated
   */
  int GATE_PERSONNEL = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GATE_PERSONNEL__NAME = EMPLOYEE__NAME;

  /**
   * The feature id for the '<em><b>Gpname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GATE_PERSONNEL__GPNAME = EMPLOYEE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Airport</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GATE_PERSONNEL__AIRPORT = EMPLOYEE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Gate Personnel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GATE_PERSONNEL_FEATURE_COUNT = EMPLOYEE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.PassengerImpl <em>Passenger</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.PassengerImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getPassenger()
   * @generated
   */
  int PASSENGER = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASSENGER__NAME = ENTITY__NAME;

  /**
   * The feature id for the '<em><b>Paname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASSENGER__PANAME = ENTITY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Specific Flight</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASSENGER__SPECIFIC_FLIGHT = ENTITY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Passenger</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASSENGER_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.airlineregistration.air.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.airlineregistration.air.Model#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entities</em>'.
   * @see org.xtext.airlineregistration.air.Model#getEntities()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Entities();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.xtext.airlineregistration.air.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.Entity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.airlineregistration.air.Entity#getName()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Airport <em>Airport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Airport</em>'.
   * @see org.xtext.airlineregistration.air.Airport
   * @generated
   */
  EClass getAirport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.Airport#getAname <em>Aname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Aname</em>'.
   * @see org.xtext.airlineregistration.air.Airport#getAname()
   * @see #getAirport()
   * @generated
   */
  EAttribute getAirport_Aname();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.Airport#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location</em>'.
   * @see org.xtext.airlineregistration.air.Airport#getLocation()
   * @see #getAirport()
   * @generated
   */
  EAttribute getAirport_Location();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Airline <em>Airline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Airline</em>'.
   * @see org.xtext.airlineregistration.air.Airline
   * @generated
   */
  EClass getAirline();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.Airline#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.airlineregistration.air.Airline#getDescription()
   * @see #getAirline()
   * @generated
   */
  EAttribute getAirline_Description();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Airplane <em>Airplane</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Airplane</em>'.
   * @see org.xtext.airlineregistration.air.Airplane
   * @generated
   */
  EClass getAirplane();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.Airplane#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.airlineregistration.air.Airplane#getType()
   * @see #getAirplane()
   * @generated
   */
  EAttribute getAirplane_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.Airplane#getSeats <em>Seats</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Seats</em>'.
   * @see org.xtext.airlineregistration.air.Airplane#getSeats()
   * @see #getAirplane()
   * @generated
   */
  EAttribute getAirplane_Seats();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.ScheduledFlight <em>Scheduled Flight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scheduled Flight</em>'.
   * @see org.xtext.airlineregistration.air.ScheduledFlight
   * @generated
   */
  EClass getScheduledFlight();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.ScheduledFlight#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>From</em>'.
   * @see org.xtext.airlineregistration.air.ScheduledFlight#getFrom()
   * @see #getScheduledFlight()
   * @generated
   */
  EReference getScheduledFlight_From();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.ScheduledFlight#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>To</em>'.
   * @see org.xtext.airlineregistration.air.ScheduledFlight#getTo()
   * @see #getScheduledFlight()
   * @generated
   */
  EReference getScheduledFlight_To();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.ScheduledFlight#getAirline <em>Airline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Airline</em>'.
   * @see org.xtext.airlineregistration.air.ScheduledFlight#getAirline()
   * @see #getScheduledFlight()
   * @generated
   */
  EReference getScheduledFlight_Airline();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.ScheduledFlight#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.xtext.airlineregistration.air.ScheduledFlight#getTime()
   * @see #getScheduledFlight()
   * @generated
   */
  EAttribute getScheduledFlight_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.SpecificFlight <em>Specific Flight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Specific Flight</em>'.
   * @see org.xtext.airlineregistration.air.SpecificFlight
   * @generated
   */
  EClass getSpecificFlight();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.SpecificFlight#getFname <em>Fname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fname</em>'.
   * @see org.xtext.airlineregistration.air.SpecificFlight#getFname()
   * @see #getSpecificFlight()
   * @generated
   */
  EAttribute getSpecificFlight_Fname();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.SpecificFlight#getScheduledFlight <em>Scheduled Flight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Scheduled Flight</em>'.
   * @see org.xtext.airlineregistration.air.SpecificFlight#getScheduledFlight()
   * @see #getSpecificFlight()
   * @generated
   */
  EReference getSpecificFlight_ScheduledFlight();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.SpecificFlight#getDate <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date</em>'.
   * @see org.xtext.airlineregistration.air.SpecificFlight#getDate()
   * @see #getSpecificFlight()
   * @generated
   */
  EAttribute getSpecificFlight_Date();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.SpecificFlight#getPilot <em>Pilot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Pilot</em>'.
   * @see org.xtext.airlineregistration.air.SpecificFlight#getPilot()
   * @see #getSpecificFlight()
   * @generated
   */
  EReference getSpecificFlight_Pilot();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.SpecificFlight#getPlane <em>Plane</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Plane</em>'.
   * @see org.xtext.airlineregistration.air.SpecificFlight#getPlane()
   * @see #getSpecificFlight()
   * @generated
   */
  EReference getSpecificFlight_Plane();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.airlineregistration.air.SpecificFlight#getStaff <em>Staff</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Staff</em>'.
   * @see org.xtext.airlineregistration.air.SpecificFlight#getStaff()
   * @see #getSpecificFlight()
   * @generated
   */
  EReference getSpecificFlight_Staff();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Schedule <em>Schedule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Schedule</em>'.
   * @see org.xtext.airlineregistration.air.Schedule
   * @generated
   */
  EClass getSchedule();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.airlineregistration.air.Schedule#getSpecificFlights <em>Specific Flights</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Specific Flights</em>'.
   * @see org.xtext.airlineregistration.air.Schedule#getSpecificFlights()
   * @see #getSchedule()
   * @generated
   */
  EReference getSchedule_SpecificFlights();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Employee <em>Employee</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Employee</em>'.
   * @see org.xtext.airlineregistration.air.Employee
   * @generated
   */
  EClass getEmployee();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Pilot <em>Pilot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pilot</em>'.
   * @see org.xtext.airlineregistration.air.Pilot
   * @generated
   */
  EClass getPilot();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.Pilot#getPiname <em>Piname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Piname</em>'.
   * @see org.xtext.airlineregistration.air.Pilot#getPiname()
   * @see #getPilot()
   * @generated
   */
  EAttribute getPilot_Piname();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.Pilot#getAirline <em>Airline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Airline</em>'.
   * @see org.xtext.airlineregistration.air.Pilot#getAirline()
   * @see #getPilot()
   * @generated
   */
  EReference getPilot_Airline();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.FlightAttendant <em>Flight Attendant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flight Attendant</em>'.
   * @see org.xtext.airlineregistration.air.FlightAttendant
   * @generated
   */
  EClass getFlightAttendant();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.FlightAttendant#getFaname <em>Faname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Faname</em>'.
   * @see org.xtext.airlineregistration.air.FlightAttendant#getFaname()
   * @see #getFlightAttendant()
   * @generated
   */
  EAttribute getFlightAttendant_Faname();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.FlightAttendant#getAirline <em>Airline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Airline</em>'.
   * @see org.xtext.airlineregistration.air.FlightAttendant#getAirline()
   * @see #getFlightAttendant()
   * @generated
   */
  EReference getFlightAttendant_Airline();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.BagHandler <em>Bag Handler</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bag Handler</em>'.
   * @see org.xtext.airlineregistration.air.BagHandler
   * @generated
   */
  EClass getBagHandler();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.BagHandler#getBhname <em>Bhname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bhname</em>'.
   * @see org.xtext.airlineregistration.air.BagHandler#getBhname()
   * @see #getBagHandler()
   * @generated
   */
  EAttribute getBagHandler_Bhname();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.BagHandler#getAirport <em>Airport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Airport</em>'.
   * @see org.xtext.airlineregistration.air.BagHandler#getAirport()
   * @see #getBagHandler()
   * @generated
   */
  EReference getBagHandler_Airport();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.GatePersonnel <em>Gate Personnel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gate Personnel</em>'.
   * @see org.xtext.airlineregistration.air.GatePersonnel
   * @generated
   */
  EClass getGatePersonnel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.GatePersonnel#getGpname <em>Gpname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Gpname</em>'.
   * @see org.xtext.airlineregistration.air.GatePersonnel#getGpname()
   * @see #getGatePersonnel()
   * @generated
   */
  EAttribute getGatePersonnel_Gpname();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.GatePersonnel#getAirport <em>Airport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Airport</em>'.
   * @see org.xtext.airlineregistration.air.GatePersonnel#getAirport()
   * @see #getGatePersonnel()
   * @generated
   */
  EReference getGatePersonnel_Airport();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Passenger <em>Passenger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Passenger</em>'.
   * @see org.xtext.airlineregistration.air.Passenger
   * @generated
   */
  EClass getPassenger();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.Passenger#getPaname <em>Paname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Paname</em>'.
   * @see org.xtext.airlineregistration.air.Passenger#getPaname()
   * @see #getPassenger()
   * @generated
   */
  EAttribute getPassenger_Paname();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.airlineregistration.air.Passenger#getSpecificFlight <em>Specific Flight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Specific Flight</em>'.
   * @see org.xtext.airlineregistration.air.Passenger#getSpecificFlight()
   * @see #getPassenger()
   * @generated
   */
  EReference getPassenger_SpecificFlight();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AirFactory getAirFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.ModelImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ENTITIES = eINSTANCE.getModel_Entities();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.EntityImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__NAME = eINSTANCE.getEntity_Name();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.AirportImpl <em>Airport</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.AirportImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getAirport()
     * @generated
     */
    EClass AIRPORT = eINSTANCE.getAirport();

    /**
     * The meta object literal for the '<em><b>Aname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AIRPORT__ANAME = eINSTANCE.getAirport_Aname();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AIRPORT__LOCATION = eINSTANCE.getAirport_Location();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.AirlineImpl <em>Airline</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.AirlineImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getAirline()
     * @generated
     */
    EClass AIRLINE = eINSTANCE.getAirline();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AIRLINE__DESCRIPTION = eINSTANCE.getAirline_Description();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.AirplaneImpl <em>Airplane</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.AirplaneImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getAirplane()
     * @generated
     */
    EClass AIRPLANE = eINSTANCE.getAirplane();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AIRPLANE__TYPE = eINSTANCE.getAirplane_Type();

    /**
     * The meta object literal for the '<em><b>Seats</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AIRPLANE__SEATS = eINSTANCE.getAirplane_Seats();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.ScheduledFlightImpl <em>Scheduled Flight</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.ScheduledFlightImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getScheduledFlight()
     * @generated
     */
    EClass SCHEDULED_FLIGHT = eINSTANCE.getScheduledFlight();

    /**
     * The meta object literal for the '<em><b>From</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEDULED_FLIGHT__FROM = eINSTANCE.getScheduledFlight_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEDULED_FLIGHT__TO = eINSTANCE.getScheduledFlight_To();

    /**
     * The meta object literal for the '<em><b>Airline</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEDULED_FLIGHT__AIRLINE = eINSTANCE.getScheduledFlight_Airline();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCHEDULED_FLIGHT__TIME = eINSTANCE.getScheduledFlight_Time();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.SpecificFlightImpl <em>Specific Flight</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.SpecificFlightImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getSpecificFlight()
     * @generated
     */
    EClass SPECIFIC_FLIGHT = eINSTANCE.getSpecificFlight();

    /**
     * The meta object literal for the '<em><b>Fname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPECIFIC_FLIGHT__FNAME = eINSTANCE.getSpecificFlight_Fname();

    /**
     * The meta object literal for the '<em><b>Scheduled Flight</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPECIFIC_FLIGHT__SCHEDULED_FLIGHT = eINSTANCE.getSpecificFlight_ScheduledFlight();

    /**
     * The meta object literal for the '<em><b>Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPECIFIC_FLIGHT__DATE = eINSTANCE.getSpecificFlight_Date();

    /**
     * The meta object literal for the '<em><b>Pilot</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPECIFIC_FLIGHT__PILOT = eINSTANCE.getSpecificFlight_Pilot();

    /**
     * The meta object literal for the '<em><b>Plane</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPECIFIC_FLIGHT__PLANE = eINSTANCE.getSpecificFlight_Plane();

    /**
     * The meta object literal for the '<em><b>Staff</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPECIFIC_FLIGHT__STAFF = eINSTANCE.getSpecificFlight_Staff();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.ScheduleImpl <em>Schedule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.ScheduleImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getSchedule()
     * @generated
     */
    EClass SCHEDULE = eINSTANCE.getSchedule();

    /**
     * The meta object literal for the '<em><b>Specific Flights</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEDULE__SPECIFIC_FLIGHTS = eINSTANCE.getSchedule_SpecificFlights();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.EmployeeImpl <em>Employee</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.EmployeeImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getEmployee()
     * @generated
     */
    EClass EMPLOYEE = eINSTANCE.getEmployee();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.PilotImpl <em>Pilot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.PilotImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getPilot()
     * @generated
     */
    EClass PILOT = eINSTANCE.getPilot();

    /**
     * The meta object literal for the '<em><b>Piname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PILOT__PINAME = eINSTANCE.getPilot_Piname();

    /**
     * The meta object literal for the '<em><b>Airline</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PILOT__AIRLINE = eINSTANCE.getPilot_Airline();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.FlightAttendantImpl <em>Flight Attendant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.FlightAttendantImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getFlightAttendant()
     * @generated
     */
    EClass FLIGHT_ATTENDANT = eINSTANCE.getFlightAttendant();

    /**
     * The meta object literal for the '<em><b>Faname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLIGHT_ATTENDANT__FANAME = eINSTANCE.getFlightAttendant_Faname();

    /**
     * The meta object literal for the '<em><b>Airline</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLIGHT_ATTENDANT__AIRLINE = eINSTANCE.getFlightAttendant_Airline();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.BagHandlerImpl <em>Bag Handler</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.BagHandlerImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getBagHandler()
     * @generated
     */
    EClass BAG_HANDLER = eINSTANCE.getBagHandler();

    /**
     * The meta object literal for the '<em><b>Bhname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BAG_HANDLER__BHNAME = eINSTANCE.getBagHandler_Bhname();

    /**
     * The meta object literal for the '<em><b>Airport</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BAG_HANDLER__AIRPORT = eINSTANCE.getBagHandler_Airport();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.GatePersonnelImpl <em>Gate Personnel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.GatePersonnelImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getGatePersonnel()
     * @generated
     */
    EClass GATE_PERSONNEL = eINSTANCE.getGatePersonnel();

    /**
     * The meta object literal for the '<em><b>Gpname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GATE_PERSONNEL__GPNAME = eINSTANCE.getGatePersonnel_Gpname();

    /**
     * The meta object literal for the '<em><b>Airport</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GATE_PERSONNEL__AIRPORT = eINSTANCE.getGatePersonnel_Airport();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.PassengerImpl <em>Passenger</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.PassengerImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getPassenger()
     * @generated
     */
    EClass PASSENGER = eINSTANCE.getPassenger();

    /**
     * The meta object literal for the '<em><b>Paname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PASSENGER__PANAME = eINSTANCE.getPassenger_Paname();

    /**
     * The meta object literal for the '<em><b>Specific Flight</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PASSENGER__SPECIFIC_FLIGHT = eINSTANCE.getPassenger_SpecificFlight();

  }

} //AirPackage
