/**
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.air;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.airlineregistration.air.AirFactory
 * @model kind="package"
 * @generated
 */
public interface AirPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "air";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/airlineregistration/Air";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "air";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AirPackage eINSTANCE = org.xtext.airlineregistration.air.impl.AirPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.ModelImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ENTITIES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.EntityImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = 0;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.AirportImpl <em>Airport</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.AirportImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getAirport()
   * @generated
   */
  int AIRPORT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT__NAME = ENTITY__NAME;

  /**
   * The feature id for the '<em><b>Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT__CODE = ENTITY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT__LOCATION = ENTITY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Airport</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.AirlineImpl <em>Airline</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.AirlineImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getAirline()
   * @generated
   */
  int AIRLINE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRLINE__NAME = ENTITY__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRLINE__DESCRIPTION = ENTITY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Airline</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRLINE_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.FlightImpl <em>Flight</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.FlightImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getFlight()
   * @generated
   */
  int FLIGHT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT__NAME = ENTITY__NAME;

  /**
   * The feature id for the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT__FROM = ENTITY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT__TO = ENTITY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Airline</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT__AIRLINE = ENTITY_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT__TIME = ENTITY_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Pilot</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT__PILOT = ENTITY_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Staff</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT__STAFF = ENTITY_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Flight</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.ScheduleImpl <em>Schedule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.ScheduleImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getSchedule()
   * @generated
   */
  int SCHEDULE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULE__NAME = ENTITY__NAME;

  /**
   * The feature id for the '<em><b>Flights</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULE__FLIGHTS = ENTITY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Schedule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULE_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.EmployeeImpl <em>Employee</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.EmployeeImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getEmployee()
   * @generated
   */
  int EMPLOYEE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE__NAME = ENTITY__NAME;

  /**
   * The number of structural features of the '<em>Employee</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.PilotImpl <em>Pilot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.PilotImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getPilot()
   * @generated
   */
  int PILOT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PILOT__NAME = EMPLOYEE__NAME;

  /**
   * The feature id for the '<em><b>Aireline</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PILOT__AIRELINE = EMPLOYEE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Pilot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PILOT_FEATURE_COUNT = EMPLOYEE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.FlightAttendantImpl <em>Flight Attendant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.FlightAttendantImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getFlightAttendant()
   * @generated
   */
  int FLIGHT_ATTENDANT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT_ATTENDANT__NAME = EMPLOYEE__NAME;

  /**
   * The feature id for the '<em><b>Aireline</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT_ATTENDANT__AIRELINE = EMPLOYEE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Flight Attendant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT_ATTENDANT_FEATURE_COUNT = EMPLOYEE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.BagHandlerImpl <em>Bag Handler</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.BagHandlerImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getBagHandler()
   * @generated
   */
  int BAG_HANDLER = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BAG_HANDLER__NAME = EMPLOYEE__NAME;

  /**
   * The feature id for the '<em><b>Airport</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BAG_HANDLER__AIRPORT = EMPLOYEE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bag Handler</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BAG_HANDLER_FEATURE_COUNT = EMPLOYEE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.airlineregistration.air.impl.GatePersonnelImpl <em>Gate Personnel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.airlineregistration.air.impl.GatePersonnelImpl
   * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getGatePersonnel()
   * @generated
   */
  int GATE_PERSONNEL = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GATE_PERSONNEL__NAME = EMPLOYEE__NAME;

  /**
   * The feature id for the '<em><b>Airport</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GATE_PERSONNEL__AIRPORT = EMPLOYEE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Gate Personnel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GATE_PERSONNEL_FEATURE_COUNT = EMPLOYEE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.airlineregistration.air.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.airlineregistration.air.Model#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entities</em>'.
   * @see org.xtext.airlineregistration.air.Model#getEntities()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Entities();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.xtext.airlineregistration.air.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.Entity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.airlineregistration.air.Entity#getName()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Airport <em>Airport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Airport</em>'.
   * @see org.xtext.airlineregistration.air.Airport
   * @generated
   */
  EClass getAirport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.Airport#getCode <em>Code</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Code</em>'.
   * @see org.xtext.airlineregistration.air.Airport#getCode()
   * @see #getAirport()
   * @generated
   */
  EAttribute getAirport_Code();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.Airport#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location</em>'.
   * @see org.xtext.airlineregistration.air.Airport#getLocation()
   * @see #getAirport()
   * @generated
   */
  EAttribute getAirport_Location();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Airline <em>Airline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Airline</em>'.
   * @see org.xtext.airlineregistration.air.Airline
   * @generated
   */
  EClass getAirline();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.Airline#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.airlineregistration.air.Airline#getDescription()
   * @see #getAirline()
   * @generated
   */
  EAttribute getAirline_Description();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Flight <em>Flight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flight</em>'.
   * @see org.xtext.airlineregistration.air.Flight
   * @generated
   */
  EClass getFlight();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.Flight#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>From</em>'.
   * @see org.xtext.airlineregistration.air.Flight#getFrom()
   * @see #getFlight()
   * @generated
   */
  EReference getFlight_From();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.Flight#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>To</em>'.
   * @see org.xtext.airlineregistration.air.Flight#getTo()
   * @see #getFlight()
   * @generated
   */
  EReference getFlight_To();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.Flight#getAirline <em>Airline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Airline</em>'.
   * @see org.xtext.airlineregistration.air.Flight#getAirline()
   * @see #getFlight()
   * @generated
   */
  EReference getFlight_Airline();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.airlineregistration.air.Flight#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.xtext.airlineregistration.air.Flight#getTime()
   * @see #getFlight()
   * @generated
   */
  EAttribute getFlight_Time();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.Flight#getPilot <em>Pilot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Pilot</em>'.
   * @see org.xtext.airlineregistration.air.Flight#getPilot()
   * @see #getFlight()
   * @generated
   */
  EReference getFlight_Pilot();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.airlineregistration.air.Flight#getStaff <em>Staff</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Staff</em>'.
   * @see org.xtext.airlineregistration.air.Flight#getStaff()
   * @see #getFlight()
   * @generated
   */
  EReference getFlight_Staff();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Schedule <em>Schedule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Schedule</em>'.
   * @see org.xtext.airlineregistration.air.Schedule
   * @generated
   */
  EClass getSchedule();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.airlineregistration.air.Schedule#getFlights <em>Flights</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Flights</em>'.
   * @see org.xtext.airlineregistration.air.Schedule#getFlights()
   * @see #getSchedule()
   * @generated
   */
  EReference getSchedule_Flights();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Employee <em>Employee</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Employee</em>'.
   * @see org.xtext.airlineregistration.air.Employee
   * @generated
   */
  EClass getEmployee();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.Pilot <em>Pilot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pilot</em>'.
   * @see org.xtext.airlineregistration.air.Pilot
   * @generated
   */
  EClass getPilot();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.Pilot#getAireline <em>Aireline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Aireline</em>'.
   * @see org.xtext.airlineregistration.air.Pilot#getAireline()
   * @see #getPilot()
   * @generated
   */
  EReference getPilot_Aireline();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.FlightAttendant <em>Flight Attendant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flight Attendant</em>'.
   * @see org.xtext.airlineregistration.air.FlightAttendant
   * @generated
   */
  EClass getFlightAttendant();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.FlightAttendant#getAireline <em>Aireline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Aireline</em>'.
   * @see org.xtext.airlineregistration.air.FlightAttendant#getAireline()
   * @see #getFlightAttendant()
   * @generated
   */
  EReference getFlightAttendant_Aireline();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.BagHandler <em>Bag Handler</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bag Handler</em>'.
   * @see org.xtext.airlineregistration.air.BagHandler
   * @generated
   */
  EClass getBagHandler();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.BagHandler#getAirport <em>Airport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Airport</em>'.
   * @see org.xtext.airlineregistration.air.BagHandler#getAirport()
   * @see #getBagHandler()
   * @generated
   */
  EReference getBagHandler_Airport();

  /**
   * Returns the meta object for class '{@link org.xtext.airlineregistration.air.GatePersonnel <em>Gate Personnel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gate Personnel</em>'.
   * @see org.xtext.airlineregistration.air.GatePersonnel
   * @generated
   */
  EClass getGatePersonnel();

  /**
   * Returns the meta object for the reference '{@link org.xtext.airlineregistration.air.GatePersonnel#getAirport <em>Airport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Airport</em>'.
   * @see org.xtext.airlineregistration.air.GatePersonnel#getAirport()
   * @see #getGatePersonnel()
   * @generated
   */
  EReference getGatePersonnel_Airport();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AirFactory getAirFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.ModelImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ENTITIES = eINSTANCE.getModel_Entities();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.EntityImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__NAME = eINSTANCE.getEntity_Name();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.AirportImpl <em>Airport</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.AirportImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getAirport()
     * @generated
     */
    EClass AIRPORT = eINSTANCE.getAirport();

    /**
     * The meta object literal for the '<em><b>Code</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AIRPORT__CODE = eINSTANCE.getAirport_Code();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AIRPORT__LOCATION = eINSTANCE.getAirport_Location();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.AirlineImpl <em>Airline</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.AirlineImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getAirline()
     * @generated
     */
    EClass AIRLINE = eINSTANCE.getAirline();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AIRLINE__DESCRIPTION = eINSTANCE.getAirline_Description();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.FlightImpl <em>Flight</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.FlightImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getFlight()
     * @generated
     */
    EClass FLIGHT = eINSTANCE.getFlight();

    /**
     * The meta object literal for the '<em><b>From</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLIGHT__FROM = eINSTANCE.getFlight_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLIGHT__TO = eINSTANCE.getFlight_To();

    /**
     * The meta object literal for the '<em><b>Airline</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLIGHT__AIRLINE = eINSTANCE.getFlight_Airline();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLIGHT__TIME = eINSTANCE.getFlight_Time();

    /**
     * The meta object literal for the '<em><b>Pilot</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLIGHT__PILOT = eINSTANCE.getFlight_Pilot();

    /**
     * The meta object literal for the '<em><b>Staff</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLIGHT__STAFF = eINSTANCE.getFlight_Staff();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.ScheduleImpl <em>Schedule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.ScheduleImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getSchedule()
     * @generated
     */
    EClass SCHEDULE = eINSTANCE.getSchedule();

    /**
     * The meta object literal for the '<em><b>Flights</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEDULE__FLIGHTS = eINSTANCE.getSchedule_Flights();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.EmployeeImpl <em>Employee</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.EmployeeImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getEmployee()
     * @generated
     */
    EClass EMPLOYEE = eINSTANCE.getEmployee();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.PilotImpl <em>Pilot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.PilotImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getPilot()
     * @generated
     */
    EClass PILOT = eINSTANCE.getPilot();

    /**
     * The meta object literal for the '<em><b>Aireline</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PILOT__AIRELINE = eINSTANCE.getPilot_Aireline();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.FlightAttendantImpl <em>Flight Attendant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.FlightAttendantImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getFlightAttendant()
     * @generated
     */
    EClass FLIGHT_ATTENDANT = eINSTANCE.getFlightAttendant();

    /**
     * The meta object literal for the '<em><b>Aireline</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLIGHT_ATTENDANT__AIRELINE = eINSTANCE.getFlightAttendant_Aireline();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.BagHandlerImpl <em>Bag Handler</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.BagHandlerImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getBagHandler()
     * @generated
     */
    EClass BAG_HANDLER = eINSTANCE.getBagHandler();

    /**
     * The meta object literal for the '<em><b>Airport</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BAG_HANDLER__AIRPORT = eINSTANCE.getBagHandler_Airport();

    /**
     * The meta object literal for the '{@link org.xtext.airlineregistration.air.impl.GatePersonnelImpl <em>Gate Personnel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.airlineregistration.air.impl.GatePersonnelImpl
     * @see org.xtext.airlineregistration.air.impl.AirPackageImpl#getGatePersonnel()
     * @generated
     */
    EClass GATE_PERSONNEL = eINSTANCE.getGatePersonnel();

    /**
     * The meta object literal for the '<em><b>Airport</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GATE_PERSONNEL__AIRPORT = eINSTANCE.getGatePersonnel_Airport();

  }

} //AirPackage
