/**
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.air;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Airplane</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.airlineregistration.air.Airplane#getAirplaneId <em>Airplane Id</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.Airplane#getAirplaneType <em>Airplane Type</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.Airplane#getSeats <em>Seats</em>}</li>
 * </ul>
 *
 * @see org.xtext.airlineregistration.air.AirPackage#getAirplane()
 * @model
 * @generated
 */
public interface Airplane extends Entity
{
  /**
   * Returns the value of the '<em><b>Airplane Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Airplane Id</em>' attribute.
   * @see #setAirplaneId(String)
   * @see org.xtext.airlineregistration.air.AirPackage#getAirplane_AirplaneId()
   * @model
   * @generated
   */
  String getAirplaneId();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.Airplane#getAirplaneId <em>Airplane Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Airplane Id</em>' attribute.
   * @see #getAirplaneId()
   * @generated
   */
  void setAirplaneId(String value);

  /**
   * Returns the value of the '<em><b>Airplane Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Airplane Type</em>' attribute.
   * @see #setAirplaneType(String)
   * @see org.xtext.airlineregistration.air.AirPackage#getAirplane_AirplaneType()
   * @model
   * @generated
   */
  String getAirplaneType();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.Airplane#getAirplaneType <em>Airplane Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Airplane Type</em>' attribute.
   * @see #getAirplaneType()
   * @generated
   */
  void setAirplaneType(String value);

  /**
   * Returns the value of the '<em><b>Seats</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seats</em>' attribute.
   * @see #setSeats(int)
   * @see org.xtext.airlineregistration.air.AirPackage#getAirplane_Seats()
   * @model
   * @generated
   */
  int getSeats();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.Airplane#getSeats <em>Seats</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Seats</em>' attribute.
   * @see #getSeats()
   * @generated
   */
  void setSeats(int value);

} // Airplane
