/**
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.air;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Airplane</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.airlineregistration.air.Airplane#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.Airplane#getSeats <em>Seats</em>}</li>
 * </ul>
 *
 * @see org.xtext.airlineregistration.air.AirPackage#getAirplane()
 * @model
 * @generated
 */
public interface Airplane extends Entity
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.xtext.airlineregistration.air.AirPackage#getAirplane_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.Airplane#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Seats</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seats</em>' attribute.
   * @see #setSeats(int)
   * @see org.xtext.airlineregistration.air.AirPackage#getAirplane_Seats()
   * @model
   * @generated
   */
  int getSeats();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.Airplane#getSeats <em>Seats</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Seats</em>' attribute.
   * @see #getSeats()
   * @generated
   */
  void setSeats(int value);

} // Airplane
