/**
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.air;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bag Handler</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.airlineregistration.air.BagHandler#getBhname <em>Bhname</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.BagHandler#getAirport <em>Airport</em>}</li>
 * </ul>
 *
 * @see org.xtext.airlineregistration.air.AirPackage#getBagHandler()
 * @model
 * @generated
 */
public interface BagHandler extends Employee
{
  /**
   * Returns the value of the '<em><b>Bhname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bhname</em>' attribute.
   * @see #setBhname(String)
   * @see org.xtext.airlineregistration.air.AirPackage#getBagHandler_Bhname()
   * @model
   * @generated
   */
  String getBhname();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.BagHandler#getBhname <em>Bhname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bhname</em>' attribute.
   * @see #getBhname()
   * @generated
   */
  void setBhname(String value);

  /**
   * Returns the value of the '<em><b>Airport</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Airport</em>' reference.
   * @see #setAirport(Airport)
   * @see org.xtext.airlineregistration.air.AirPackage#getBagHandler_Airport()
   * @model
   * @generated
   */
  Airport getAirport();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.BagHandler#getAirport <em>Airport</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Airport</em>' reference.
   * @see #getAirport()
   * @generated
   */
  void setAirport(Airport value);

} // BagHandler
