/**
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.air;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gate Personnel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.airlineregistration.air.GatePersonnel#getGpname <em>Gpname</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.GatePersonnel#getAirport <em>Airport</em>}</li>
 * </ul>
 *
 * @see org.xtext.airlineregistration.air.AirPackage#getGatePersonnel()
 * @model
 * @generated
 */
public interface GatePersonnel extends Employee
{
  /**
   * Returns the value of the '<em><b>Gpname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gpname</em>' attribute.
   * @see #setGpname(String)
   * @see org.xtext.airlineregistration.air.AirPackage#getGatePersonnel_Gpname()
   * @model
   * @generated
   */
  String getGpname();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.GatePersonnel#getGpname <em>Gpname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gpname</em>' attribute.
   * @see #getGpname()
   * @generated
   */
  void setGpname(String value);

  /**
   * Returns the value of the '<em><b>Airport</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Airport</em>' reference.
   * @see #setAirport(Airport)
   * @see org.xtext.airlineregistration.air.AirPackage#getGatePersonnel_Airport()
   * @model
   * @generated
   */
  Airport getAirport();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.GatePersonnel#getAirport <em>Airport</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Airport</em>' reference.
   * @see #getAirport()
   * @generated
   */
  void setAirport(Airport value);

} // GatePersonnel
