/**
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.air;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Passenger</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.airlineregistration.air.Passenger#getPaname <em>Paname</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.Passenger#getSpecificFlight <em>Specific Flight</em>}</li>
 * </ul>
 *
 * @see org.xtext.airlineregistration.air.AirPackage#getPassenger()
 * @model
 * @generated
 */
public interface Passenger extends Entity
{
  /**
   * Returns the value of the '<em><b>Paname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paname</em>' attribute.
   * @see #setPaname(String)
   * @see org.xtext.airlineregistration.air.AirPackage#getPassenger_Paname()
   * @model
   * @generated
   */
  String getPaname();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.Passenger#getPaname <em>Paname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Paname</em>' attribute.
   * @see #getPaname()
   * @generated
   */
  void setPaname(String value);

  /**
   * Returns the value of the '<em><b>Specific Flight</b></em>' reference list.
   * The list contents are of type {@link org.xtext.airlineregistration.air.SpecificFlight}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Specific Flight</em>' reference list.
   * @see org.xtext.airlineregistration.air.AirPackage#getPassenger_SpecificFlight()
   * @model
   * @generated
   */
  EList<SpecificFlight> getSpecificFlight();

} // Passenger
