/**
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.air;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Schedule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.airlineregistration.air.Schedule#getSpecificFlights <em>Specific Flights</em>}</li>
 * </ul>
 *
 * @see org.xtext.airlineregistration.air.AirPackage#getSchedule()
 * @model
 * @generated
 */
public interface Schedule extends Entity
{
  /**
   * Returns the value of the '<em><b>Specific Flights</b></em>' reference list.
   * The list contents are of type {@link org.xtext.airlineregistration.air.SpecificFlight}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Specific Flights</em>' reference list.
   * @see org.xtext.airlineregistration.air.AirPackage#getSchedule_SpecificFlights()
   * @model
   * @generated
   */
  EList<SpecificFlight> getSpecificFlights();

} // Schedule
