/**
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.air;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scheduled Flight</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.airlineregistration.air.ScheduledFlight#getFrom <em>From</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.ScheduledFlight#getTo <em>To</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.ScheduledFlight#getAirline <em>Airline</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.ScheduledFlight#getTime <em>Time</em>}</li>
 * </ul>
 *
 * @see org.xtext.airlineregistration.air.AirPackage#getScheduledFlight()
 * @model
 * @generated
 */
public interface ScheduledFlight extends Entity
{
  /**
   * Returns the value of the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' reference.
   * @see #setFrom(Airport)
   * @see org.xtext.airlineregistration.air.AirPackage#getScheduledFlight_From()
   * @model
   * @generated
   */
  Airport getFrom();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.ScheduledFlight#getFrom <em>From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(Airport value);

  /**
   * Returns the value of the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' reference.
   * @see #setTo(Airport)
   * @see org.xtext.airlineregistration.air.AirPackage#getScheduledFlight_To()
   * @model
   * @generated
   */
  Airport getTo();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.ScheduledFlight#getTo <em>To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' reference.
   * @see #getTo()
   * @generated
   */
  void setTo(Airport value);

  /**
   * Returns the value of the '<em><b>Airline</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Airline</em>' reference.
   * @see #setAirline(Airline)
   * @see org.xtext.airlineregistration.air.AirPackage#getScheduledFlight_Airline()
   * @model
   * @generated
   */
  Airline getAirline();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.ScheduledFlight#getAirline <em>Airline</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Airline</em>' reference.
   * @see #getAirline()
   * @generated
   */
  void setAirline(Airline value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' attribute.
   * @see #setTime(String)
   * @see org.xtext.airlineregistration.air.AirPackage#getScheduledFlight_Time()
   * @model
   * @generated
   */
  String getTime();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.ScheduledFlight#getTime <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' attribute.
   * @see #getTime()
   * @generated
   */
  void setTime(String value);

} // ScheduledFlight
