/**
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.air;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Specific Flight</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.airlineregistration.air.SpecificFlight#getFname <em>Fname</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.SpecificFlight#getScheduledFlight <em>Scheduled Flight</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.SpecificFlight#getDate <em>Date</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.SpecificFlight#getPilot <em>Pilot</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.SpecificFlight#getPlane <em>Plane</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.SpecificFlight#getStaff <em>Staff</em>}</li>
 * </ul>
 *
 * @see org.xtext.airlineregistration.air.AirPackage#getSpecificFlight()
 * @model
 * @generated
 */
public interface SpecificFlight extends Entity
{
  /**
   * Returns the value of the '<em><b>Fname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fname</em>' attribute.
   * @see #setFname(String)
   * @see org.xtext.airlineregistration.air.AirPackage#getSpecificFlight_Fname()
   * @model
   * @generated
   */
  String getFname();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.SpecificFlight#getFname <em>Fname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fname</em>' attribute.
   * @see #getFname()
   * @generated
   */
  void setFname(String value);

  /**
   * Returns the value of the '<em><b>Scheduled Flight</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scheduled Flight</em>' reference.
   * @see #setScheduledFlight(ScheduledFlight)
   * @see org.xtext.airlineregistration.air.AirPackage#getSpecificFlight_ScheduledFlight()
   * @model
   * @generated
   */
  ScheduledFlight getScheduledFlight();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.SpecificFlight#getScheduledFlight <em>Scheduled Flight</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scheduled Flight</em>' reference.
   * @see #getScheduledFlight()
   * @generated
   */
  void setScheduledFlight(ScheduledFlight value);

  /**
   * Returns the value of the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date</em>' attribute.
   * @see #setDate(String)
   * @see org.xtext.airlineregistration.air.AirPackage#getSpecificFlight_Date()
   * @model
   * @generated
   */
  String getDate();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.SpecificFlight#getDate <em>Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date</em>' attribute.
   * @see #getDate()
   * @generated
   */
  void setDate(String value);

  /**
   * Returns the value of the '<em><b>Pilot</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pilot</em>' reference.
   * @see #setPilot(Pilot)
   * @see org.xtext.airlineregistration.air.AirPackage#getSpecificFlight_Pilot()
   * @model
   * @generated
   */
  Pilot getPilot();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.SpecificFlight#getPilot <em>Pilot</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pilot</em>' reference.
   * @see #getPilot()
   * @generated
   */
  void setPilot(Pilot value);

  /**
   * Returns the value of the '<em><b>Plane</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plane</em>' reference.
   * @see #setPlane(Airplane)
   * @see org.xtext.airlineregistration.air.AirPackage#getSpecificFlight_Plane()
   * @model
   * @generated
   */
  Airplane getPlane();

  /**
   * Sets the value of the '{@link org.xtext.airlineregistration.air.SpecificFlight#getPlane <em>Plane</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plane</em>' reference.
   * @see #getPlane()
   * @generated
   */
  void setPlane(Airplane value);

  /**
   * Returns the value of the '<em><b>Staff</b></em>' reference list.
   * The list contents are of type {@link org.xtext.airlineregistration.air.FlightAttendant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Staff</em>' reference list.
   * @see org.xtext.airlineregistration.air.AirPackage#getSpecificFlight_Staff()
   * @model
   * @generated
   */
  EList<FlightAttendant> getStaff();

} // SpecificFlight
