/*
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAirScopeProvider extends DelegatingScopeProvider {
}
