/*
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.airlineregistration.AirRuntimeModule;
import org.xtext.airlineregistration.AirStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AirIdeSetup extends AirStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AirRuntimeModule(), new AirIdeModule()));
	}
	
}
