/**
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.air.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.airlineregistration.air.AirPackage;
import org.xtext.airlineregistration.air.Airplane;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Airplane</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.airlineregistration.air.impl.AirplaneImpl#getAirplaneId <em>Airplane Id</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.impl.AirplaneImpl#getAirplaneType <em>Airplane Type</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.impl.AirplaneImpl#getSeats <em>Seats</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AirplaneImpl extends EntityImpl implements Airplane
{
  /**
   * The default value of the '{@link #getAirplaneId() <em>Airplane Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAirplaneId()
   * @generated
   * @ordered
   */
  protected static final String AIRPLANE_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAirplaneId() <em>Airplane Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAirplaneId()
   * @generated
   * @ordered
   */
  protected String airplaneId = AIRPLANE_ID_EDEFAULT;

  /**
   * The default value of the '{@link #getAirplaneType() <em>Airplane Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAirplaneType()
   * @generated
   * @ordered
   */
  protected static final String AIRPLANE_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAirplaneType() <em>Airplane Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAirplaneType()
   * @generated
   * @ordered
   */
  protected String airplaneType = AIRPLANE_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getSeats() <em>Seats</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeats()
   * @generated
   * @ordered
   */
  protected static final int SEATS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSeats() <em>Seats</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeats()
   * @generated
   * @ordered
   */
  protected int seats = SEATS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AirplaneImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AirPackage.Literals.AIRPLANE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAirplaneId()
  {
    return airplaneId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAirplaneId(String newAirplaneId)
  {
    String oldAirplaneId = airplaneId;
    airplaneId = newAirplaneId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AirPackage.AIRPLANE__AIRPLANE_ID, oldAirplaneId, airplaneId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAirplaneType()
  {
    return airplaneType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAirplaneType(String newAirplaneType)
  {
    String oldAirplaneType = airplaneType;
    airplaneType = newAirplaneType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AirPackage.AIRPLANE__AIRPLANE_TYPE, oldAirplaneType, airplaneType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getSeats()
  {
    return seats;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSeats(int newSeats)
  {
    int oldSeats = seats;
    seats = newSeats;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AirPackage.AIRPLANE__SEATS, oldSeats, seats));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AirPackage.AIRPLANE__AIRPLANE_ID:
        return getAirplaneId();
      case AirPackage.AIRPLANE__AIRPLANE_TYPE:
        return getAirplaneType();
      case AirPackage.AIRPLANE__SEATS:
        return getSeats();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AirPackage.AIRPLANE__AIRPLANE_ID:
        setAirplaneId((String)newValue);
        return;
      case AirPackage.AIRPLANE__AIRPLANE_TYPE:
        setAirplaneType((String)newValue);
        return;
      case AirPackage.AIRPLANE__SEATS:
        setSeats((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AirPackage.AIRPLANE__AIRPLANE_ID:
        setAirplaneId(AIRPLANE_ID_EDEFAULT);
        return;
      case AirPackage.AIRPLANE__AIRPLANE_TYPE:
        setAirplaneType(AIRPLANE_TYPE_EDEFAULT);
        return;
      case AirPackage.AIRPLANE__SEATS:
        setSeats(SEATS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AirPackage.AIRPLANE__AIRPLANE_ID:
        return AIRPLANE_ID_EDEFAULT == null ? airplaneId != null : !AIRPLANE_ID_EDEFAULT.equals(airplaneId);
      case AirPackage.AIRPLANE__AIRPLANE_TYPE:
        return AIRPLANE_TYPE_EDEFAULT == null ? airplaneType != null : !AIRPLANE_TYPE_EDEFAULT.equals(airplaneType);
      case AirPackage.AIRPLANE__SEATS:
        return seats != SEATS_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (airplaneId: ");
    result.append(airplaneId);
    result.append(", airplaneType: ");
    result.append(airplaneType);
    result.append(", seats: ");
    result.append(seats);
    result.append(')');
    return result.toString();
  }

} //AirplaneImpl
