/**
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.air.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.airlineregistration.air.AirPackage;
import org.xtext.airlineregistration.air.Airline;
import org.xtext.airlineregistration.air.Pilot;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pilot</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.airlineregistration.air.impl.PilotImpl#getAireline <em>Aireline</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PilotImpl extends EmployeeImpl implements Pilot
{
  /**
   * The cached value of the '{@link #getAireline() <em>Aireline</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAireline()
   * @generated
   * @ordered
   */
  protected Airline aireline;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PilotImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AirPackage.Literals.PILOT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Airline getAireline()
  {
    if (aireline != null && aireline.eIsProxy())
    {
      InternalEObject oldAireline = (InternalEObject)aireline;
      aireline = (Airline)eResolveProxy(oldAireline);
      if (aireline != oldAireline)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AirPackage.PILOT__AIRELINE, oldAireline, aireline));
      }
    }
    return aireline;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Airline basicGetAireline()
  {
    return aireline;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAireline(Airline newAireline)
  {
    Airline oldAireline = aireline;
    aireline = newAireline;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AirPackage.PILOT__AIRELINE, oldAireline, aireline));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AirPackage.PILOT__AIRELINE:
        if (resolve) return getAireline();
        return basicGetAireline();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AirPackage.PILOT__AIRELINE:
        setAireline((Airline)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AirPackage.PILOT__AIRELINE:
        setAireline((Airline)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AirPackage.PILOT__AIRELINE:
        return aireline != null;
    }
    return super.eIsSet(featureID);
  }

} //PilotImpl
