/**
 * generated by Xtext 2.26.0
 */
package org.xtext.airlineregistration.air.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.airlineregistration.air.AirPackage;
import org.xtext.airlineregistration.air.Airline;
import org.xtext.airlineregistration.air.Airport;
import org.xtext.airlineregistration.air.ScheduledFlight;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Scheduled Flight</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.airlineregistration.air.impl.ScheduledFlightImpl#getFrom <em>From</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.impl.ScheduledFlightImpl#getTo <em>To</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.impl.ScheduledFlightImpl#getAirline <em>Airline</em>}</li>
 *   <li>{@link org.xtext.airlineregistration.air.impl.ScheduledFlightImpl#getTime <em>Time</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ScheduledFlightImpl extends EntityImpl implements ScheduledFlight
{
  /**
   * The cached value of the '{@link #getFrom() <em>From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFrom()
   * @generated
   * @ordered
   */
  protected Airport from;

  /**
   * The cached value of the '{@link #getTo() <em>To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTo()
   * @generated
   * @ordered
   */
  protected Airport to;

  /**
   * The cached value of the '{@link #getAirline() <em>Airline</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAirline()
   * @generated
   * @ordered
   */
  protected Airline airline;

  /**
   * The default value of the '{@link #getTime() <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTime()
   * @generated
   * @ordered
   */
  protected static final String TIME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTime() <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTime()
   * @generated
   * @ordered
   */
  protected String time = TIME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ScheduledFlightImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AirPackage.Literals.SCHEDULED_FLIGHT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Airport getFrom()
  {
    if (from != null && from.eIsProxy())
    {
      InternalEObject oldFrom = (InternalEObject)from;
      from = (Airport)eResolveProxy(oldFrom);
      if (from != oldFrom)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AirPackage.SCHEDULED_FLIGHT__FROM, oldFrom, from));
      }
    }
    return from;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Airport basicGetFrom()
  {
    return from;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFrom(Airport newFrom)
  {
    Airport oldFrom = from;
    from = newFrom;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AirPackage.SCHEDULED_FLIGHT__FROM, oldFrom, from));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Airport getTo()
  {
    if (to != null && to.eIsProxy())
    {
      InternalEObject oldTo = (InternalEObject)to;
      to = (Airport)eResolveProxy(oldTo);
      if (to != oldTo)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AirPackage.SCHEDULED_FLIGHT__TO, oldTo, to));
      }
    }
    return to;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Airport basicGetTo()
  {
    return to;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTo(Airport newTo)
  {
    Airport oldTo = to;
    to = newTo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AirPackage.SCHEDULED_FLIGHT__TO, oldTo, to));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Airline getAirline()
  {
    if (airline != null && airline.eIsProxy())
    {
      InternalEObject oldAirline = (InternalEObject)airline;
      airline = (Airline)eResolveProxy(oldAirline);
      if (airline != oldAirline)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AirPackage.SCHEDULED_FLIGHT__AIRLINE, oldAirline, airline));
      }
    }
    return airline;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Airline basicGetAirline()
  {
    return airline;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAirline(Airline newAirline)
  {
    Airline oldAirline = airline;
    airline = newAirline;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AirPackage.SCHEDULED_FLIGHT__AIRLINE, oldAirline, airline));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTime()
  {
    return time;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTime(String newTime)
  {
    String oldTime = time;
    time = newTime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AirPackage.SCHEDULED_FLIGHT__TIME, oldTime, time));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AirPackage.SCHEDULED_FLIGHT__FROM:
        if (resolve) return getFrom();
        return basicGetFrom();
      case AirPackage.SCHEDULED_FLIGHT__TO:
        if (resolve) return getTo();
        return basicGetTo();
      case AirPackage.SCHEDULED_FLIGHT__AIRLINE:
        if (resolve) return getAirline();
        return basicGetAirline();
      case AirPackage.SCHEDULED_FLIGHT__TIME:
        return getTime();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AirPackage.SCHEDULED_FLIGHT__FROM:
        setFrom((Airport)newValue);
        return;
      case AirPackage.SCHEDULED_FLIGHT__TO:
        setTo((Airport)newValue);
        return;
      case AirPackage.SCHEDULED_FLIGHT__AIRLINE:
        setAirline((Airline)newValue);
        return;
      case AirPackage.SCHEDULED_FLIGHT__TIME:
        setTime((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AirPackage.SCHEDULED_FLIGHT__FROM:
        setFrom((Airport)null);
        return;
      case AirPackage.SCHEDULED_FLIGHT__TO:
        setTo((Airport)null);
        return;
      case AirPackage.SCHEDULED_FLIGHT__AIRLINE:
        setAirline((Airline)null);
        return;
      case AirPackage.SCHEDULED_FLIGHT__TIME:
        setTime(TIME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AirPackage.SCHEDULED_FLIGHT__FROM:
        return from != null;
      case AirPackage.SCHEDULED_FLIGHT__TO:
        return to != null;
      case AirPackage.SCHEDULED_FLIGHT__AIRLINE:
        return airline != null;
      case AirPackage.SCHEDULED_FLIGHT__TIME:
        return TIME_EDEFAULT == null ? time != null : !TIME_EDEFAULT.equals(time);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (time: ");
    result.append(time);
    result.append(')');
    return result.toString();
  }

} //ScheduledFlightImpl
